export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';

export const GET_POKEMONS_START = 'GET_POKEMONS_START';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR';

export const GET_SINGLE_POKEMON_START = 'GET_SINGLE_POKEMON_START';
export const GET_SINGLE_POKEMON_SUCCESS = 'GET_SINGLE_POKEMON_SUCCESS';
export const GET_SINGLE_POKEMON_ERROR = 'GET_SINGLE_POKEMON_ERROR';
